### ISSUE TITLE
logging module usage

### ISSUE THREAD

**Issue by XAMeLeOH** [bwsw/moebius#12]
Typical logging usage:
------------------------------------------------------------------
.............
import logging
import........

logger = logging(__name__)

.....................

def my_func(*args, **kwargs):
    logger.debug("entering into my_func with args: %s", "|".join(args))
    ..............

------------------------------------------------------------------

So in future you will be able to differ log messages from different modules.

**Comment by bwsw** [comment]
Fixed in Pull Req #13
